version: "3.8"
services:
    king-spring-service:
        build: .
        ports:
            - "${PORT}:8080"
        env_file:
            - .env
        environment:
            - DB_NAME=${DB_NAME}
            - DB_USERNAME=${DB_USERNAME}
            - DB_PASSWORD=${DB_PASSWORD}
